### PR TITLE
Grounded knowledge

### PR DESCRIPTION
**Pull request by AndrewBuck**
Adding basic GroundedKnowledge class which shows how to load in atoms at bot init time.  Currently it just writes in a bunch of info about which blocks can be mined with what tool, as well as what they yeild when they are mined out.

### CODE REVIEW

**Comment by rTreutlein** [comment]
Hey currently the systems uses BlockIDs not Names. Which makes a bit more Sense for an Computer System. So change your code to do that Aswell.

You could also change the existing code to use Names it shouldn't make a big difference for OpenCog, but that seems like a lot more work.

**Comment by AndrewBuck** [comment]
I think it is worth it to store concepts in the atomspace in more useful name formats, or at least ones more sensible to humans.  For names of blocks I am using the output of one of the spockbot functions which reads from the minecraft data python package to get the names.  The names it is using look pretty decent, however a few of them have the same display name for different variations of blocks.  I think it is worth correcting these few instances though, rather than trying to stick with only numbered concepts in the atomspace as writing rules and things like that will be much simpler.  The grounded knowledge code does need to be tweaked a bit though, because the names I was using there do not match the ones in the spockbot implementation.  This should be easy enough to fix though.

**Comment by AndrewBuck** [comment]
Ok, so I modified the block loading grounded knowledge routine to use one similar to what spockbot does.  It creates a ConceptNode atom for every "kind" of block (the atom's name is human readable).  It also creates predicates linking every kind of block to the information about what integer it is stored as in minecraft and similarly for the hardness of each type.  The file I am reading also contains info on what kind of tools can be used to mine out the different blocks.  This is not currently being read in but will be in the future.

**Comment by AmeBel** [comment]
there is a merge conflict, pls update

**Comment by AndrewBuck** [comment]
Ugh, I messed up.  I intended for commit ac310db to be on a different branch.  That commit breaks the bot so this pull request should NOT be merged now.  I will poke around on the code a bit and see about getting it working, or we may just have to merge in from the pull before that and fix the conflict again (which is easy, the conflict is just me changing the readme to note that the bot now walks toward wood blocks, not gold ore).

**Pull request closed without merging**
