### PR TITLE
Goals

### PR DESCRIPTION
**Pull request by AndrewBuck**
Load a list of goals into the atomspace (examples: 'look around', 'rest', 'explore', 'gather resources', etc).  There is one goal linked to as the 'CURRENT_GOAL' which is the one the bot will take action in the next time step to try to meet that goal.  At the end of each time step a random number is chosen to decide if we should keep working on the same goal, or switch to something else.  We are more likely to switch if we have been on this goal for a long time, and less likely to switch if we are making good progress towards meeting this goal.  If we are no longer making progress towards meeting the goal we are very likely to switch to something else.

### CODE REVIEW

**Comment by AndrewBuck** [comment]
The bot now updates the short term importance on the tiles in its vision and also has slightly improved, but still hacky, movement code.

**Comment by fredyvilla** [comment]
Andrew, Is this PR ready to be closed? Is it tied to any tasks?

**Comment by AndrewBuck** [comment]
Explore is to have the bot find new areas of the map, discover is to find the first instance of a particular block type (for example the first time you have seen diamond ore).  Not sure if that really should be a goal of its own or just a reward that any time it happens just boost the bots current happiness level, sort of like an achievement.

The list of goals at the moment is very preliminary.  Basically when I wrote the code that loaded them into the atomspace I wanted to have a few as examples in addition to what I already had so I just made up a few simple ones.  We should probably also have ones like 'farm' or 'breed animals' for gathering food as well as maybe others like 'hunting', etc.

**Comment by AndrewBuck** [comment]
The PR could be merged at any time, the code is stable and does work.  The bot will occasionally walk through 1 or 2 block thick walls, due to the hacky routing code we have now, but that code will be replaced by a totally different routing algorithm anyway so it is not worth fixing in this code.

It is not tied to any specific tasks on the waffle board.  There is code in the 'explore' goal but I would not say that it is enough progress on it to consider it finished yet so I would just merge this pull request so others can develop further from here.

**Comment by AndrewBuck** [comment]
This last commit just fixes that issue with the extra file listed in Cmakelists.txt

**Pull request merged**
