### PR TITLE
Removing DOS special characters to fix rosrun & adding troubleshooting.sh script

### PR DESCRIPTION
**Pull request by fredyvilla**
Removing DOS special characters to fix rosrun & adding troubleshooting.sh script.

### CODE REVIEW

**Comment by fredyvilla** [comment]
Sending a new pull request where I already merged the latest from opencog/opencog-to-minecraft

**Comment by AmeBel** [comment]
you don't need to, whatever changes you make to the branch you made a pr from is mirrored

**Comment by AmeBel** [comment]
just mention when you are done

**Comment by fredyvilla** [comment]
I'm done with all of my commits.

**Pull request merged**
